version: '3'
services:
  api:
    build:
      context: ./api
    ports:
      - "3000:3000"
    networks:
      - app-network

  client:
    build:
      context: ./client
    ports:
      - "4000:4000"
    depends_on:
      - api
    networks:
      - app-network
    environment:
      API_URL: http://api:3000  # Nombre del servicio API (se puede usar como host en Docker Compose)

networks:
  app-network:
    driver: bridge
