# docker-compose.yml
services:
  api:
    build: ./api
    ports:
      - "3000:3000"
    volumes:
      - ./coverage/api:/app/coverage # Compartir cobertura API
    networks:
      - app-network

  client:
    build: ./client
    ports:
      - "4000:4000"
    depends_on:
      - api
    volumes:
      - ./coverage/client:/app/coverage # Compartir cobertura Cliente
    networks:
      - app-network

networks:
  app-network:
    driver: bridge