version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-master
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home  # Volumen para los datos de Jenkins
      - /var/run/docker.sock:/var/run/docker.sock  # Montar el socket Docker de la máquina anfitriona
    networks:
      - app-network
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock  # Establecer el host Docker
    privileged: true  # Permite acceso completo a Docker

volumes:
  jenkins_home:  # Volumen persistente para Jenkins

networks:
  app-network:
    driver: bridge
